# Generated by Django 3.2.5 on 2021-07-30 22:23

import app_shakil.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_shakil', '0002_auto_20210731_0328'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='blog_image',
            field=models.ImageField(blank=True, null=True, upload_to=app_shakil.models.filepath),
        ),
    ]
