# Generated by Django 3.2.5 on 2021-07-31 21:38

import app_shakil.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_shakil', '0003_alter_blog_blog_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Work',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_image', models.ImageField(blank=True, null=True, upload_to=app_shakil.models.filepath)),
                ('work_title', models.CharField(max_length=200)),
                ('work_tools', models.CharField(max_length=200)),
                ('work_url', models.CharField(max_length=200)),
            ],
        ),
    ]
